org: adapttive
app: preview
service: preview

frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221


package:
  patterns:
    - bin/ping
    - bin/preview

functions:
  ping:
    handler: bin/ping
    events:
      - http:
          path: /ping
          method: get
          cors:
            origin: '*'
  preview:
    handler: bin/preview
    events:
      - http:
          path: /preview
          cors:
            origin: '*'
          method: post
          request:
            template:
              application/x-www-form-urlencoded: '{"body" : "$input.body"}'


