name: Deploy main branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/setup-go@v2
        with:
          node-version: '^1.13.1'
      - run: |
          go version
          go build -v -ldflags "-d -s -w" -a -tags netgo -installsuffix netgo -o bin/ping ping/main.go
          go build -v -ldflags "-d -s -w" -a -tags netgo -installsuffix netgo -o bin/preview preview/main.go
      - name: serverless deploy
        uses: serverless/github-action@v3
        with:
          args: deploy
        env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}